- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

  	- name: Create T3ier VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: T3vpcout
      
    - debug:
        var: T3vpcout
        
    - name: create public subnet1 for web in zone1
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-WEB-1a
      register: T3pubsub1zone1web_out
    
    - name: create public subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-WEB-1b
      register: T3pubsub1zone2web_out

    - name: create public subnet3 for app in zone1
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-APP-1a
      register: T3pubsub3zone1app_out
    
    - name: create public subnet4 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-APP-1b
      register: T3pubsub4zone2app_out

    - name: create public subnet5 for db in zone1
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub5cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-DB-1a
      register: T3pubsub5zone1db_out
    
    - name: create public subnet6 for db in zone2
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-DB-1b
      register: T3pubsub6zone2db_out
