- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  	- name: Import VPC variables
  	  include_vars: vars/vpc_setup

  	- name: Create 3T VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: 3Tvpcout
      
    - debug:
        var: 3Tvpcout