- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create T3ier VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: T3vpcout
      
    - debug:
        var: T3vpcout
        
    - name: create public subnet1 for web in zone1
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-WEB-1a
      register: T3pubsub1zone1web_out
    
    - name: create public subnet2 for web in zone2
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        resource_tags:
          Name: T3-WEB-1b
      register: T3pubsub1zone2web_out

    - name: create public subnet3 for app in zone1
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub3cidr}}"
        map_public: no
        resource_tags:
          Name: T3-APP-1a
      register: T3pubsub3zone1app_out
    
    - name: create public subnet4 for app in zone2
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: no
        resource_tags:
          Name: T3-APP-1b
      register: T3pubsub4zone2app_out

    - name: create public subnet5 for db in zone1
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub5cidr}}"
        map_public: no
        resource_tags:
          Name: T3-DB-1a
      register: T3pubsub5zone1db_out
    
    - name: create public subnet6 for db in zone2
      ec2_vpc_subnet:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub6cidr}}"
        map_public: no
        resource_tags:
          Name: T3-DB-1b
      register: T3pubsub6zone2db_out
    - name: Internet Gateway Setup
      ec2_vpc_igw:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: T3_IGW
      register: T3_igw_out

    - name: Setup Public Subnet Route Table
      ec2_vpc_route_table:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: T3-PUBLIC-RT
        subnets:
          - "{{T3pubsub1zone1web_out.subnet.id}}"
          - "{{T3pubsub1zone2web_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{T3_igw_out.gateway_id}}"
      register: T3_pubRT_out

    - name: Create new NAT gateway fro T3 webapp
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: "{{T3pubsub1zone1web_out.subnet.id}}"
        wait: yes
        region: "{{region}}"
        if_exist_do_not_create: true
      register: T3_NATGW_out

    - name: Setup private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: T3-PRIVATE-RT
        subnets:
          - "{{T3pubsub3zone1app_out.subnet.id}}"
          - "{{T3pubsub4zone2app_out.subnet.id}}"
          - "{{T3pubsub5zone1db_out.subnet.id}}"
          - "{{T3pubsub6zone2db_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{T3_NATGW_out.nat_gateway_id}}"
      register: T3_privRT_out
      
    - name: sg for 3 Tier public
      ec2_group:
        name: "T3-PUBLIC-SG"
        description: allow 22,80,ICMP from everywhere
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22

      register: T3PUBLICSG

    - name: sg for 3 Tier APP
      ec2_group:
        name: "T3-APP-SG"
        description: allow 22,ICMP from everywhere
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{T3PUBLICSG.group_id}}"
            rule_desc: allow all on port 80

      register: T3APPSG
    
    
    - name: Create ec2 key for adding into launch templates
      ec2_key:
        name: T3-key
        region: "{{region}}"
      register: key_out


    - name: Save private key into file T3-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./T3-key.pem"
        mode: 0600
      when: key_out.changed
      
    - debug:
        var: "{{item}}"
      loop:
        - T3vpcout.vpc.id
        - T3pubsub3zone1app_out.subnet.id
        - T3pubsub4zone2app_out.subnet.id
        - T3pubsub5zone1db_out.subnet.id
        - T3pubsub6zone2db_out.subnet.id
        - T3pubsub1zone1web_out.subnet.id
        - T3pubsub1zone2web_out.subnet.id
        - T3_igw_out.gateway_id
        - T3_pubRT_out.route_table.id
        - T3_NATGW_out.nat_gateway_id
        - T3_privRT_out.route_table.id

    - name: create variables file for VPC output
      copy:
        content: "vpcid: {{T3vpcout.vpc.id}}\npubsub1id: {{T3pubsub1zone1web_out.subnet.id}}\npubsub2id: {{T3pubsub1zone2web_out.subnet.id}}\npubsub3id: {{T3pubsub3zone1app_out.subnet.id.subnet.id}}\nprivsub1id: {{T3pubsub4zone2app_out.subnet.id.subnet.id}}\nprivsub2id: {{T3pubsub5zone1db_out.subnet.id}}\nprivsub3id: {{T3pubsub6zone2db_out.subnet.id}}\nigwid: {{T3_igw_out.gateway_id}}\npubRTid: {{T3_pubRT_out.route_table.id}}\nNATGWid: {{T3_NATGW_out.nat_gateway_id}}\nprivRTid: {{T3_privRT_out.route_table.id}}\n"
        dest: vars/output_vars
