- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

  	- name: Create 3Tier VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: 3Tvpcout
      
    - debug:
        var: 3Tvpcout
        
    - name: create public subnet1 for web in zone1
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-WEB-1a
      register: 3Tpubsub1zone1web_out
    
    - name: create public subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-WEB-1b
      register: 3Tpubsub1zone2web_out

    - name: create public subnet3 for app in zone1
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-APP-1a
      register: 3Tpubsub3zone1app_out
    
    - name: create public subnet4 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-APP-1b
      register: 3Tpubsub4zone2app_out

    - name: create public subnet5 for db in zone1
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub5cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-DB-1a
      register: 3Tpubsub5zone1db_out
    
    - name: create public subnet6 for db in zone2
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-DB-1b
      register: 3Tpubsub6zone2db_out
