- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
      
    - name: Import the tasks from 3T_VPC_setup.yml
      import_tasks: 3T_VPC_setup.yml

    - name: Create Launch Configuration for web tier
      ec2_lc:
        name: my-launch-config-test
        image_id: ami-0cc87e5027adcdca8
        instance_type: t2.micro
        key_name: T3-key
        region: "{{region}}"
        security_groups: "{{my3tierwebsg.group_id}}"
        user_data: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<html><body><h1>Welcome to the web tier!</h1></body></html>" > /var/www/html/index.html
    
    - name: Create Auto Scaling Group
      ec2_asg:
        name: my-test-asg
        launch_config_name: my-launch-config-test
        vpc_zone_identifier: ["{{T3pubsub1zone1_out.subnet.id}}", "{{T3pubsub2zone2_out.subnet.id}}"]
        min_size: 2
        max_size: 4
        desired_capacity: 2
        region: "{{region}}"
