- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    - name: Creating Auto Scaling Group for web tier 
      autoscaling_group:
        name: webtier-asg
        load_balancers: []
        availability_zones: [ "{{zone1}}", "{{zone2}}" ]
        launch_template:
          version: '1'
          launch_template_name: 'my-3tier-launch'
        min_size: 2
        max_size: 4
        desired_capacity: 2
        vpc_zone_identifier: [ "{{pubsub1cidr}}", "{{pubsub2cidr}}" ]
        tags:
          - environment: 3 tier
