- name: Example RDS creation playbook
  hosts: localhost
  gather_facts: false
  vars:
    region: us-west-2
    db_instance_identifier: mydbinstance
    db_instance_class: db.t2.micro
    db_engine: mysql
    db_engine_version: "5.7"
    db_name: mydb
    db_username: myuser
    db_password: mypassword
    vpc_security_group_ids:
      - sg-0123456789abcdef
  tasks:
    - name: Create RDS instance
      rds:
        command: create
        region: "{{ region }}"
        db_instance_identifier: "{{ db_instance_identifier }}"
        db_instance_class: "{{ db_instance_class }}"
        engine: "{{ db_engine }}"
        engine_version: "{{ db_engine_version }}"
        db_name: "{{ db_name }}"
        username: "{{ db_username }}"
        password: "{{ db_password }}"
        vpc_security_group_ids: "{{ vpc_security_group_ids }}"
