- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create T3ier VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: T3vpcout
      
    - debug:
        var: T3vpcout
    
    - name: example using security group rule descriptions
      amazon.aws.ec2_security_group:
        name: "Sample SG"
        description: allow 80 from everywhere
        vpc_id: "{{T3vpcout.vpc.id}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
